### ISSUE TITLE
As a Developer I want a database model for User

### ISSUE THREAD

**Issue by JoePotentier** [CMPUT404-Group-Project/Distributed-Social-Networking#1]
# Author should have:
## ID of the Author (UUID)
Example: 1d698d25ff008f7538453c120f581471
## url to the authors information
Example: http://127.0.0.1:5454/author/1d698d25ff008f7538453c120f581471
## Host:
Example: http://127.0.0.1:5454/
## Display name:
Example: Greg Johnson
## HATEOS url for Github API
Example: http://github.com/gjohnson

**Comment by KenRLi** [comment]
Mostly done, need to fix password displayed in a text box
