### ISSUE TITLE
As an author, I want a method to view the public posts from other nodes

### ISSUE THREAD

**Issue by ColonelSanders21** [CMPUT404-Group-Project/Distributed-Social-Networking#135]
Add an "Explore" page to pull in the public posts and users from the Nodes we are registered with

**Comment by JoePotentier** [comment]
"Explore" tab in addition to the "Stream" on the homepage. Which displays public posts from other nodes.

**Comment by JoePotentier** [comment]
Let's chat about this one when you are online.

**Comment by kalegar** [comment]
> 
> 
> Let's chat about this one when you are online.

Sure! I've just pushed a branch (FRNT/135-Explore-Tab) that splits the homepage into two tabs, 'Stream' and 'Explore'. The Explore tab pulls foreign posts via an ajax call to a new api endpoint, /posts/foreign
