### ISSUE TITLE
As a server admin, I want our database to match the status of remote nodes

### ISSUE THREAD

**Issue by KenRLi** [CMPUT404-Group-Project/Distributed-Social-Networking#202]
Update our database when remote nodes update or delete an author or post

**Comment by JoePotentier** [comment]
Should split this up into Author, Posts, Comments, Friends etc.

**Comment by KenRLi** [comment]
I was thinking when we call GET remote/api/author/post/ (#148), we check the author information against our DB and check all post id against our DB and update if necessary
